// Feature: honey-bee-power-webshop, Property 12: Checkout Form Zod Validation Gate
// Validates: Requirements 13.12

import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'
import { validateCheckoutForm } from '@/features/checkout/schema'
import type { CheckoutFormValues } from '@/types'

// ---------------------------------------------------------------------------
// Helper: valid form fixture
// ---------------------------------------------------------------------------

function validForm(overrides: Partial<CheckoutFormValues> = {}): Partial<CheckoutFormValues> {
  return {
    fullName: 'Ana Horvat',
    email: 'ana.horvat@example.com',
    phone: '+38512345678',
    address: 'Ilica 1',
    city: 'Zagreb',
    postalCode: '10000',
    country: 'HR',
    paymentMethod: 'card',
    deliveryMethod: 'hp_express',
    isGuestCheckout: true,
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** Any non-empty string of length >= 2 — valid fullName candidates. */
const validFullNameArb = fc.string({ minLength: 2, maxLength: 100 }).filter(
  (s) => s.trim().length >= 2,
)

/** Strings of length 0 or 1 (trimmed) — invalid fullName candidates. */
const shortStringArb = fc.oneof(
  fc.constant(''),
  fc.constant(' '),
  fc.string({ minLength: 1, maxLength: 1 }),
)

/** Simple valid emails generated by fast-check. */
const validEmailArb = fc
  .tuple(
    fc.stringMatching(/^[a-z]{2,8}$/),
    fc.stringMatching(/^[a-z]{2,8}$/),
    fc.stringMatching(/^[a-z]{2,4}$/),
  )
  .map(([user, domain, tld]) => `${user}@${domain}.${tld}`)

/** Invalid emails — strings without @ or domain structure. */
const invalidEmailArb = fc.oneof(
  fc.constant('not-an-email'),
  fc.constant('missing@domain'),
  fc.constant('@nodomain.com'),
  fc.constant('nodot@nodot'),
  fc.constant(''),
  fc.constant('   '),
)

/** postalCode shorter than 4 characters. */
const shortPostalCodeArb = fc.oneof(
  fc.constant(''),
  fc.constant('1'),
  fc.constant('12'),
  fc.constant('123'),
)

// ---------------------------------------------------------------------------
// Property tests
// ---------------------------------------------------------------------------

describe('Checkout Form Validation — Property 12: Checkout Form Zod Validation Gate', () => {
  /**
   * Property: A fully valid form produces an empty errors object.
   * No spurious validation errors should block a correct submission.
   *
   * Validates: Requirements 13.12
   */
  it('returns no errors for a valid form', () => {
    fc.assert(
      fc.property(validFullNameArb, validEmailArb, (fullName, email) => {
        const form = validForm({ fullName, email })
        const errors = validateCheckoutForm(form)
        expect(Object.keys(errors)).toHaveLength(0)
      }),
      { numRuns: 100 },
    )
  })

  /**
   * Property: A form with an empty or too-short fullName always has a fullName error.
   *
   * Validates: Requirements 13.12
   */
  it('reports a fullName error when fullName is empty or too short', () => {
    fc.assert(
      fc.property(shortStringArb, (badName) => {
        const form = validForm({ fullName: badName })
        const errors = validateCheckoutForm(form)
        expect(errors.fullName).toBeTruthy()
      }),
      { numRuns: 100 },
    )
  })

  /**
   * Property: A form with an invalid email always has an email error.
   *
   * Validates: Requirements 13.12
   */
  it('reports an email error when email is invalid', () => {
    fc.assert(
      fc.property(invalidEmailArb, (badEmail) => {
        const form = validForm({ email: badEmail })
        const errors = validateCheckoutForm(form)
        expect(errors.email).toBeTruthy()
      }),
      { numRuns: 100 },
    )
  })

  /**
   * Property: A form with a postalCode shorter than 4 characters always has a
   * postalCode error.
   *
   * Validates: Requirements 13.12
   */
  it('reports a postalCode error when postalCode is too short', () => {
    fc.assert(
      fc.property(shortPostalCodeArb, (badPostal) => {
        const form = validForm({ postalCode: badPostal })
        const errors = validateCheckoutForm(form)
        expect(errors.postalCode).toBeTruthy()
      }),
      { numRuns: 100 },
    )
  })

  // ---------------------------------------------------------------------------
  // Concrete examples
  // ---------------------------------------------------------------------------

  it('valid form: no errors returned', () => {
    const errors = validateCheckoutForm(validForm())
    expect(Object.keys(errors)).toHaveLength(0)
  })

  it('empty fullName → fullName error', () => {
    const errors = validateCheckoutForm(validForm({ fullName: '' }))
    expect(errors.fullName).toBeTruthy()
  })

  it('single-char fullName → fullName error', () => {
    const errors = validateCheckoutForm(validForm({ fullName: 'A' }))
    expect(errors.fullName).toBeTruthy()
  })

  it('invalid email format → email error', () => {
    const errors = validateCheckoutForm(validForm({ email: 'not-valid' }))
    expect(errors.email).toBeTruthy()
  })

  it('missing @ in email → email error', () => {
    const errors = validateCheckoutForm(validForm({ email: 'userdomain.com' }))
    expect(errors.email).toBeTruthy()
  })

  it('3-char postalCode → postalCode error', () => {
    const errors = validateCheckoutForm(validForm({ postalCode: '100' }))
    expect(errors.postalCode).toBeTruthy()
  })

  it('4-char postalCode → no postalCode error', () => {
    const errors = validateCheckoutForm(validForm({ postalCode: '1000' }))
    expect(errors.postalCode).toBeUndefined()
  })

  it('valid form with optional phone omitted → no errors', () => {
    const errors = validateCheckoutForm(validForm({ phone: undefined }))
    expect(Object.keys(errors)).toHaveLength(0)
  })
})
